source 'https://github.com/Cocoapods/Specs.git'

flutter_application_path = './hotu_module'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')


inhibit_all_warnings!
target 'hotu' do
  install_all_flutter_pods(flutter_application_path)
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Alamofire'
  pod 'SDWebImage'
  pod 'IQKeyboardManager'
  pod 'MJRefresh', "3.2.2"
  pod 'WechatOpenSDK', "1.8.1"
  pod 'HandyJSON'
  pod 'SwiftyJSON'
  pod 'RongCloudIM'
  pod 'MBProgressHUD'
  pod 'AFNetworking'
  pod 'UMCShare/Social/ReducedQQ'
  pod 'BRPickerView'
  pod 'YYText'
  pod 'BmobSDK'
end
